### ISSUE TITLE
Display higher resolution timing on trips tab

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/dtm#1]
Adding millisecond resolution to timestamps displayed on the Trips tab may aid in correlation with PV signals.   I believe we only have NTP keeping clocks synchronized, but that should be good down to 10s of milliseconds.

**Comment by slominskir** [comment]
The FSD_TRIP table START_DATE_UTC and END_DATE_UTC are DATE columns, which does not include milliseconds.   This is going to be a major change (it's not just a display format tweak).  The FSD Logger daemon that inserts records into the table would need to be updated too.

**Comment by CJSlominski** [comment]
Note that ioc PV updates are not made when the event occurs, but when it is noticed by the periodic epics scan tasks running on the IOC. These are typically 1-second periods, but sometimes 2-second. The periodic epics tasks are not synchronized between iocs. Adding more numeric resolution to correlate PVs hosted by different iocs will have little meaning.

**Comment by slominskir** [comment]
Closing per comment above.
